name: rbsc
recipe: drupal7
config:
  php: '8.1'
  webroot: .
services:
  search:
    type: solr:custom
    overrides:
      image: pulibrary/ci-solr:8.4-v1.0.0
      command: server/scripts/lando-start.sh
    core: rbsc
    portforward: 9999
    config:
      dir: sites/all/modules/contrib/search_api_solr/solr-conf/7.x
  node:
    type: 'node:8'
    globals:
      gulp-cli: latest
    overrides:
      platform: linux/x86_64
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
