<?php

// Plugin definition
$plugin = array(
  'title' => t('Grid Menu'),
  'category' => t('Grid Menu'),
  'icon' => 'grid-menu.png',
  'theme' => 'grid-menu',
  'css' => 'grid-menu.css',
  'regions' => array(
    'featured' => t('Featured'),
    'grid-A' => t('Grid A'),
    'grid-B' => t('Grid B'),
    'grid-C' => t('Grid C'),
    'grid-D' => t('Grid D'),
    'grid-E' => t('Grid E'),
    'grid-F' => t('Grid F'),
    'rbsc-desc' => t('RBSC Description'),
    'rbsc-news' => t('New and Notable')
  ),
);
